version: "3.9"
services:
  bitcoin-core:
    container_name: bitcoin
    image: docker.io/ruimarinho/bitcoin-core:23.0-alpine
    restart: unless-stopped
    volumes:
        - "path/to/data/dir:/home/bitcoin/.bitcoin"
    ports:
      - "8333:8333"
      - "127.0.0.1:8332:8332"
      - "127.0.0.1:28332:28332"
      - "127.0.0.1:28333:28333"
    command:
        -listen
        -rpcbind=0.0.0.0
        -rpcallowip=0.0.0.0/0
        -rpcauth="bitcoinrpc:xxxxx"
        -zmqpubrawblock=tcp://0.0.0.0:28332
        -zmqpubrawtx=tcp://0.0.0.0:28333
        -assumevalid=0000000000000000000149b8c8a1ca8f9685b6c81b991262a8470c678a290d2e
        -server=1
        -blockfilterindex=1
        -peerblockfilters=1
        -debug=mempool
        -debug=rpc
        -maxuploadtarget=1000
        -dbcache=8000
        -txindex
      
networks:
  default:
    name: baremetal
    external: true
