version: "3.9"
services:
  bitcoin-core:
    container_name: bitcoin-core
    image: docker.io/ruimarinho/bitcoin-core:23.0-alpine
    restart: unless-stopped
    volumes:
        - "~/.bitcoin:/home/bitcoin/.bitcoin"
    ports:
      - "28332:28332"
      - "28333:28333"
      - "8332:8332"


  lnd:
    container_name: lnd
    image: docker.io/lightninglabs/lnd:v0.16.0-beta
    restart: unless-stopped
    depends_on: ['bitcoin-core']
    volumes: 
      - ~/.lnd:/root/.lnd
    ports:
      - "9735:9735"
      - "10009:10009"

networks:
  default:
    name: baremetal
    external: true

