version: '3.9'
services:
  electrs:
    container_name: electrs
    image: docker.io/niteshbalusu/electrs:amd64 # There is also an arm64 version available.
    command: "electrs --network=bitcoin --db-dir=/data --daemon-dir=/bitcoin --daemon-rpc-addr=bitcoin:8332 --daemon-p2p-addr=bitcoin:8333 --log-filters=INFO"
    restart: on-failure
    volumes:
      - path/to/bitcoin/data/dir:/bitcoin:ro
      - path/to/electrs/data/dir:/data
    ports:
      - "50001:50001"

    stop_grace_period: 5m
networks:
  default:
    name: baremetal
    external: true
