version: "3.9"
services:
  lnd-testnet:
    container_name: lnd
    image: docker.io/lightninglabs/lnd:v0.15.5-beta
    restart: unless-stopped
    volumes: 
      - path/to/lnd/dir:/root/.lnd
    ports:
      - "9735:9735"
      - "10009:10009"

    command:
        lnd
        --accept-keysend
        --alias="Yo!" # Set you alias
        --allow-circular-route
        --debuglevel=CNCT=debug,CRTR=debug,HSWC=debug,NTFN=debug,RPCS=debug
        --externalip=123.123.123.123 # Your clearnet IP
        --gc-canceled-invoices-on-startup
        --gc-canceled-invoices-on-the-fly
        --ignore-historical-gossip-filters
        --listen=0.0.0.0:9735
        --maxpendingchannels=10
        --rpclisten=0.0.0.0:10009
        --bitcoin.active
        --bitcoin.mainnet
        --bitcoin.node=bitcoind
        --bitcoin.timelockdelta=144
        --bitcoin.defaultchanconfs=2
        --bitcoind.rpcpass="xxxxx" # Set bitcoin-core rpc password
        --bitcoind.rpcuser=bitcoinrpc
        --bitcoind.zmqpubrawblock=tcp://bitcoin-core:28332
        --bitcoind.zmqpubrawtx=tcp://bitcoin-core:28333
        --bitcoind.rpchost="bitcoin:8332"
        --db.bolt.auto-compact
        --protocol.wumbo-channels
        --routing.strictgraphpruning
        --tlsextradomain=lnd
        --tlsextraip=123.123.123.123 # Your clearnet IP
        --wallet-unlock-password-file=/root/.lnd/wallet_password
        
networks:
  default:
    name: baremetal
    external: true

